services:
  server:
    build:
      context: ./visavi-server
    ports:
      - "5000:5000"
    env_file:
      - ./visavi-server/.env
    volumes:
      - ./visavi-server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: ./visavi-client
    ports:
      - "5173:5173"
    volumes:
      - ./visavi-client:/app
      - /app/node_modules
    command: npm run dev
